repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
      # exclude generated files
      exclude: \.cls$|\.bst$

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    - id: codespell
      files: ^.*\.(md|tex)$
      args: ["-w", "-L", "hist,gaus"]
